# Generated by Django 5.0.1 on 2024-07-05 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер велосипеда')),
                ('is_rented', models.BooleanField(default=False, verbose_name='Статус велосипеда')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Начало аренды')),
                ('finish_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Конец аренды')),
                ('value', models.IntegerField(blank=True, default=None, null=True, verbose_name='Стоимость аренды')),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='bicycles.bicycle', verbose_name='Велосипед')),
            ],
        ),
    ]
